import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/Providers/ThemeProvider";
import { Toaster } from "react-hot-toast";
import axios from "axios";
import { Provider } from "react-redux";
import { store } from "@/store/store";
import { Providers } from "@/components/Providers/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

axios.defaults.baseURL = "https://api.themoviedb.org/3/";
axios.defaults.headers.common[
  "Authorization"
] = `Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMzQzYjI4NDRkM2NkYTQzNTgwMGI4MjI2YTlkNDQ2MiIsIm5iZiI6MTc0NTkwMTU1Mi40ODg5OTk4LCJzdWIiOiI2ODEwNTdmMDJlOGJhMDIyZTQ4MGQzMmYiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0._iUiceSDI57B4wy6IdMEhrK6uRgcxL5Ytf1sAWxsH9U`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          <Providers>
            <div className={"min-h-screen"}>
              <main className={""}>
                {children} <Toaster />
              </main>
            </div>
          </Providers>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
